
var Prototype={Version:'1.4.0_pre10_ajax',emptyFunction:function(){},K:function(x){return x}};var Class={create:function(){return function(){this.initialize.apply(this,arguments);}}};var Abstract=new Object();Object.extend=function(destination,source){for(property in source){destination[property]=source[property];}
return destination;};Object.inspect=function(object){try{if(object==undefined)return'undefined';if(object==null)return'null';return object.inspect?object.inspect():object.toString();}catch(e){if(e instanceof RangeError)return'...';throw e;}};Function.prototype.bind=function(object){var __method=this;return function(){return __method.apply(object,arguments);};};Function.prototype.bindAsEventListener=function(object){var __method=this;return function(event){return __method.call(object,event||window.event);};};Object.extend(Number.prototype,{toColorPart:function(){var digits=this.toString(16);if(this<16)return'0'+digits;return digits;},succ:function(){return this+1;},times:function(iterator){$R(0,this,true).each(iterator);return this;}});var Try={these:function(){var returnValue;for(var i=0;i<arguments.length;i++){var lambda=arguments[i];try{returnValue=lambda();break;}catch(e){}}
return returnValue;}};var PeriodicalExecuter=Class.create();PeriodicalExecuter.prototype={initialize:function(callback,frequency){this.callback=callback;this.frequency=frequency;this.currentlyExecuting=false;this.registerCallback();},registerCallback:function(){setInterval(this.onTimerEvent.bind(this),this.frequency*1000);},onTimerEvent:function(){if(!this.currentlyExecuting){try{this.currentlyExecuting=true;this.callback();}finally{this.currentlyExecuting=false;}}}};function $(){var elements=new Array();for(var i=0;i<arguments.length;i++){var element=arguments[i];if(typeof element=='string')
element=document.getElementById(element);if(arguments.length==1)
return element;elements.push(element);}
return elements;};var Ajax={getTransport:function(){return Try.these(function(){return new ActiveXObject('Msxml2.XMLHTTP')},function(){return new ActiveXObject('Microsoft.XMLHTTP')},function(){return new XMLHttpRequest()})||false;}};Ajax.Base=function(){};Ajax.Base.prototype={setOptions:function(options){this.options={method:'post',asynchronous:true,parameters:''};Object.extend(this.options,options||{});},responseIsSuccess:function(){return this.transport.status==undefined||this.transport.status==0||(this.transport.status>=200&&this.transport.status<300);},responseIsFailure:function(){return!this.responseIsSuccess();}};Ajax.Request=Class.create();Ajax.Request.Events=['Uninitialized','Loading','Loaded','Interactive','Complete'];Ajax.Request.prototype=Object.extend(new Ajax.Base(),{initialize:function(url,options){this.transport=Ajax.getTransport();this.setOptions(options);this.request(url);},request:function(url){var parameters=this.options.parameters||'';if(parameters.length>0)parameters+='&_=';try{if(this.options.method=='get')
url+='?'+parameters;this.transport.open(this.options.method,url,this.options.asynchronous);if(this.options.asynchronous){this.transport.onreadystatechange=this.onStateChange.bind(this);setTimeout((function(){this.respondToReadyState(1)}).bind(this),10);}
this.setRequestHeaders();var body=this.options.postBody?this.options.postBody:parameters;this.transport.send(this.options.method=='post'?body:null);}catch(e){};},setRequestHeaders:function(){var requestHeaders=['X-Requested-With','XMLHttpRequest','X-Prototype-Version',Prototype.Version];if(this.options.method=='post'){requestHeaders.push('Content-type','application/x-www-form-urlencoded');if(this.transport.overrideMimeType)requestHeaders.push('Connection','close');}
if(this.options.requestHeaders)
requestHeaders.push.apply(requestHeaders,this.options.requestHeaders);for(var i=0;i<requestHeaders.length;i+=2)
this.transport.setRequestHeader(requestHeaders[i],requestHeaders[i+1]);},onStateChange:function(){var readyState=this.transport.readyState;if(readyState!=1)
this.respondToReadyState(this.transport.readyState);},evalJSON:function(){try{var json=this.transport.getResponseHeader('X-JSON'),object;object=eval(json);return object;}catch(e){}},respondToReadyState:function(readyState){var event=Ajax.Request.Events[readyState];var transport=this.transport,json=this.evalJSON();if(event=='Complete')
(this.options['on'+this.transport.status]||this.options['on'+(this.responseIsSuccess()?'Success':'Failure')]||Prototype.emptyFunction)(transport,json);(this.options['on'+event]||Prototype.emptyFunction)(transport,json);if(event=='Complete')
this.transport.onreadystatechange=Prototype.emptyFunction;}});Ajax.Updater=Class.create();Ajax.Updater.ScriptFragment='(?:<script.*?>)((\n|.)*?)(?:<\/script>)';Object.extend(Object.extend(Ajax.Updater.prototype,Ajax.Request.prototype),{initialize:function(container,url,options){this.containers={success:container.success?$(container.success):$(container),failure:container.failure?$(container.failure):(container.success?null:$(container))};this.transport=Ajax.getTransport();this.setOptions(options);var onComplete=this.options.onComplete||Prototype.emptyFunction;this.options.onComplete=(function(transport,object){this.updateContent();onComplete(transport,object);}).bind(this);this.request(url);},updateContent:function(){var receiver=this.responseIsSuccess()?this.containers.success:this.containers.failure;var match=new RegExp(Ajax.Updater.ScriptFragment,'img');var response=this.transport.responseText.replace(match,'');var scripts=this.transport.responseText.match(match);if(receiver){if(this.options.insertion){new this.options.insertion(receiver,response);}else{receiver.innerHTML=response;}}
if(this.responseIsSuccess()){if(this.onComplete)
setTimeout(this.onComplete.bind(this),10);}
if(this.options.evalScripts&&scripts){match=new RegExp(Ajax.Updater.ScriptFragment,'im');setTimeout((function(){for(var i=0;i<scripts.length;i++)
eval(scripts[i].match(match)[1]);}).bind(this),10);}}});Ajax.PeriodicalUpdater=Class.create();Ajax.PeriodicalUpdater.prototype=Object.extend(new Ajax.Base(),{initialize:function(container,url,options){this.setOptions(options);this.onComplete=this.options.onComplete;this.frequency=(this.options.frequency||2);this.decay=1;this.updater={};this.container=container;this.url=url;this.start();},start:function(){this.options.onComplete=this.updateComplete.bind(this);this.onTimerEvent();},stop:function(){this.updater.onComplete=undefined;clearTimeout(this.timer);(this.onComplete||Ajax.emptyFunction).apply(this,arguments);},updateComplete:function(request){if(this.options.decay){this.decay=(request.responseText==this.lastText?this.decay*this.options.decay:1);this.lastText=request.responseText;}
this.timer=setTimeout(this.onTimerEvent.bind(this),this.decay*this.frequency*1000);},onTimerEvent:function(){this.updater=new Ajax.Updater(this.container,this.url,this.options);}});var tooltip=function(){var id='tt';var top=3;var left=11;var maxw=670;var speed=5;var timer=10;var endalpha=95;var alpha=0;var accept_fade=0;var tt,t,c,b,h;tt=$('tt');var ie=document.all?true:false;return{show:function(v,w){if(!tt){tt=document.createElement('div');tt.setAttribute('id',id);t=document.createElement('div');t.setAttribute('id',id+'top');c=document.createElement('div');c.setAttribute('id',id+'cont');b=document.createElement('div');b.setAttribute('id',id+'bot');tt.appendChild(t);tt.appendChild(c);tt.appendChild(b);document.body.appendChild(tt);if(accept_fade)tt.style.opacity=0;if(accept_fade)tt.style.filter='alpha(opacity=0)';document.onmousemove=this.pos;}
tt.style.display='block';c.innerHTML=v;tt.style.width=w?w+'px':'auto';if(!w&&ie){t.style.display='none';b.style.display='none';tt.style.width=tt.offsetWidth;t.style.display='block';b.style.display='block';}
if(tt.offsetWidth>maxw){tt.style.width=maxw+'px'}
h=parseInt(tt.offsetHeight)+top;if(accept_fade){clearInterval(tt.timer);tt.timer=setInterval(function(){tooltip.fade(1)},timer);}},pos:function(e){var u=ie?event.clientY+document.documentElement.scrollTop:e.pageY;var l=ie?event.clientX+document.documentElement.scrollLeft:e.pageX;var scrolledX,scrolledY;if(window.pageYOffset){scrolledX=window.pageXOffset;scrolledY=window.pageYOffset;}
else if(document.documentElement&&document.documentElement.scrollTop){scrolledX=document.documentElement.scrollLeft;scrolledY=document.documentElement.scrollTop;}
else if(document.body){scrolledX=document.body.scrollLeft;scrolledY=document.body.scrollTop;}
tt.style.top=(((u-scrolledY-h)>0)?((u-h)+'px'):(u+'px'));tt.style.left=(l+left)+'px';},fade:function(d){var a=alpha;if((a!=endalpha&&d==1)||(a!=0&&d==-1)){var i=speed;if(endalpha-a<speed&&d==1){i=endalpha-a;}else if(alpha<speed&&d==-1){i=a;}
alpha=a+(i*d);tt.style.opacity=alpha*.01;tt.style.filter='alpha(opacity='+alpha+')';}else{clearInterval(tt.timer);if(d==-1){tt.style.display='none'}}},hide:function(){if(accept_fade){clearInterval(tt.timer);tt.timer=setInterval(function(){tooltip.fade(-1)},timer);}else{tt.style.display='none';}}};}();function BulleWrite(txt_,e_,x_,y_){tooltip.show(txt_);}
function BulleHide(){tooltip.hide();}
function insertText(formName,txtToAdd){var txtObj=eval(formName);if(navigator.appName=="Microsoft Internet Explorer")
{var str=document.selection.createRange().text;txtObj.focus();var sel=document.selection.createRange();sel.text=str+txtToAdd;return;}
else
{oldPos=txtObj.scrollTop;oldHght=txtObj.scrollHeight;pos=txtObj.selectionEnd+txtToAdd.length;txtObj.value=txtObj.value.substr(0,txtObj.selectionStart)+
txtObj.value.substr(txtObj.selectionStart,txtObj.selectionEnd-txtObj.selectionStart)+
txtToAdd+txtObj.value.substr(txtObj.selectionEnd);txtObj.selectionStart=pos;txtObj.selectionEnd=pos;newHght=txtObj.scrollHeight-oldHght;txtObj.scrollTop=oldPos+newHght;}
txtObj.focus();};var sas_tmstp=Math.round(Math.random()*10000000000);var sas_masterflag=1;function SmartAdServer(sas_pageid,sas_formatid,sas_target){if(sas_masterflag==1){sas_masterflag=0;sas_master='M';}
else{sas_master='S';}
document.write('<scr'+'ipt ID="SmartScr'+sas_formatid+'" SRC="http://www3.smartadserver.com/call/pubj/'+sas_pageid+'/'+sas_formatid+'/'+sas_master+'/'+sas_tmstp+'/'+escape(sas_target)+'?"></scr'+'ipt>');};var adOnTop=1;var scriptStrip=0;var adBottom=null;function magicLinkUpdate(requete){var txtObj=eval('document.ajout.message');if(navigator.appName=="Microsoft Internet Explorer"){var str=document.selection.createRange().text;txtObj.focus();var sel=document.selection.createRange();sel.text=requete.responseText;}
else{oldPos=txtObj.scrollTop;oldHght=txtObj.scrollHeight;pos=txtObj.selectionEnd;txtObj.value=txtObj.value.substr(0,txtObj.selectionStart)+requete.responseText+
txtObj.value.substr(txtObj.selectionEnd);txtObj.selectionStart=pos;txtObj.selectionEnd=pos;newHght=txtObj.scrollHeight-oldHght;txtObj.scrollTop=oldPos+newHght;}};function magicLink(){var txtObj=eval('document.ajout.message');txtObj.focus();if(navigator.appName=="Microsoft Internet Explorer"){var str=document.selection.createRange().text;txtObj.focus();}
else{var str=txtObj.value.substr(txtObj.selectionStart,txtObj.selectionEnd-txtObj.selectionStart);}
var url="/remote/magiclink.php3";var pars="text="+escape(str);var myAjax=new Ajax.Request(url,{method:"post",postBody:pars,onComplete:magicLinkUpdate});};function insertTag(txtName,tag,enclose){var closeTag=((enclose)?"</"+tag+">":"");var Tag="<"+tag+">";var txtObj=eval(txtName);if(navigator.appName=="Microsoft Internet Explorer")
{var str=document.selection.createRange().text;txtObj.focus();var sel=document.selection.createRange();sel.text=Tag+str+closeTag;return;}
else
{oldPos=txtObj.scrollTop;oldHght=txtObj.scrollHeight;pos=txtObj.selectionEnd+Tag.length+closeTag.length;txtObj.value=txtObj.value.substr(0,txtObj.selectionStart)+Tag+
txtObj.value.substr(txtObj.selectionStart,txtObj.selectionEnd-txtObj.selectionStart)+
closeTag+txtObj.value.substr(txtObj.selectionEnd);txtObj.selectionStart=pos;txtObj.selectionEnd=pos;newHght=txtObj.scrollHeight-oldHght;txtObj.scrollTop=oldPos+newHght;}
txtObj.focus();};function PutThat(url){window.open(url,"_blank","location=yes,toolbar=yes,directories=yes,status=yes, menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes");};function GetParam(name){var match=new RegExp(name+"=(.+)[&]","i").exec(location.search);if(match==null){match=new RegExp(name+"=(.+)","i").exec(location.search);}
if(match==null){return null;}
match=match+"";result=match.split(",");return result[1];};ref_k='';function refk(){var ptn=/google[.]/i;var q='';if(ref_k){q=ref_k;}
else{if(ptn.exec(document.referrer)!=null){var u_p=document.referrer.split('?');if(u_p[1]){var u_a=u_p[1].split('&');for(var i=0;i<u_a.length;i++){var kv=u_a[i].split('=');if(kv[0]=='q'){q=decodeURIComponent(kv[1]).replace(/(allinanchor|allintext|allintitle|allinurl|author|cache|define|filetype|group|id|inanchor|info|insubject|intext|intitle|inurl|location|phonebook|related|rphonebook|site|source)[:][^ +]+/,'');q=q.replace(/[+]/g,' ');}}}}
ref_k=q;}
return q;};function strip_accents(str){var s=str;var rExps=[/[\xC0-\xC2]/g,/[\xE0-\xE2]/g,/[\xC8-\xCA]/g,/[\xE8-\xEB]/g,/[\xCC-\xCE]/g,/[\xEC-\xEE]/g,/[\xD2-\xD4]/g,/[\xF2-\xF4]/g,/[\xD9-\xDB]/g,/[\xF9-\xFB]/g];var repChar=['A','a','E','e','I','i','O','o','U','u'];for(var i=0;i<rExps.length;i++)
s=s.replace(rExps[i],repChar[i]);return s;};function compareStringLengths(a,b){if(a.length<b.length)
return 1;if(a.length>b.length)
return-1;return 0;};function h_j(te,container){var gtc='#000000';var glc=new Array('#ffff66','#a0ffff','#99ff99','#ff9999','#ff66ff');var reg=new RegExp("[-:;,+=(){}/?<>!*'\\\"\\[\\]\\ ]+","g");var words=strip_accents(te).toLowerCase().split(reg);words.sort(compareStringLengths);if(words.length>0){var c=0;for(var i=0;i<words.length;i++){if(words[i].length>1&&container){h_g(words[i],container,glc[c]);c=(c==glc.length-1)?0:c+1;}}}}
function h_g(te,container,color){var t_l=te.toLowerCase();for(var i=0;i<container.childNodes.length;i++){var node=container.childNodes[i];if(node.nodeType==3){var data=node.data;var d_l=strip_accents(data.toLowerCase());if(d_l.indexOf(t_l)!=-1){var n_n=document.createElement('span');node.parentNode.replaceChild(n_n,node);var res;while((res=d_l.indexOf(t_l))!=-1){n_n.appendChild(document.createTextNode(data.substr(0,res)));n_n.appendChild(c_n_g(document.createTextNode(data.substr(res,te.length)),color));data=data.substr(res+te.length);d_l=d_l.substr(res+te.length);}
n_n.appendChild(document.createTextNode(data));}}
else{h_g(te,node,color);}}};function c_n_g(child,color){var node=document.createElement('span');node.style.fontWeight='bold';node.appendChild(child);return node;};gg_afs_query='';function google_afs_request_done(google_ads){var google_num_ads=google_ads.length;if(google_num_ads<=0){return;}
var wideAds="";var narrowAds="";for(i=0;i<google_num_ads;i++){if(google_ads[i].type=="text/wide"){wideAds+='<div class="gaBlock_afs"';wideAds+=' onmouseover="window.status=\'Visiter '+google_ads[i].visible_url+'\'" onmouseout="window.status=\'\'">';wideAds+='<a href="'+google_ads[i].url+'" onclick="PutThat(\''+google_ads[i].url+'\');return false;" class="gaTitle">'+google_ads[i].line1+'</a><br/>';wideAds+='<span class="gaText">'+google_ads[i].line2+'</span><br/>';wideAds+='<a href='+google_ads[i].url+'"" onclick="PutThat(\''+google_ads[i].url+'\');return false;" class="gaUrl">'+google_ads[i].visible_url+'</a><br/>';wideAds+='</div><div class="omber" style="margin-bottom:5px"></div>';}else{narrowAds+='<div class="gaBlock" style="padding:6px"';narrowAds+=' onmouseover="window.status=\'Visiter '+google_ads[i].visible_url+'\'" onmouseout="window.status=\'\'">';narrowAds+='<a href="'+google_ads[i].url+'" onclick="PutThat(\''+google_ads[i].url+'\');return false;" class="gaTitle">'+google_ads[i].line1+'</a><br/>';narrowAds+='<span class="gaText">'+google_ads[i].line2+'&nbsp;'+google_ads[i].line3+'</span><br/>';narrowAds+='<a href="'+google_ads[i].url+'" onclick="PutThat(\''+google_ads[i].url+'\');return false;" class="gaUrl">'+google_ads[i].visible_url+'</a><br/>';narrowAds+='</div>';}}
feedbck='<h1><a href="http://services.google.com/feedback/online_hws_feedback" class="gh1" target="_blank">Annonces Google</a></h1>';feedsmall='<div align="right" style="padding:3px"><a href="http://services.google.com/feedback/online_hws_feedback" class="gg1" target="_blank">Annonces Google</a></div>';if(narrowAds!="")narrowAds=feedbck+narrowAds;if(wideAds!="")wideAds=feedsmall+wideAds;$('wide_ad_unit').innerHTML=wideAds;$('narrow_ad_unit').innerHTML=narrowAds;h_j(gg_afs_query,$('wide_ad_unit'));};